import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import "./theme-config.css";
import { Theme, ThemePanel } from "@radix-ui/themes";

const inter = Nunito({ subsets: ["latin"], variable: "--font-nunito" });

export const metadata: Metadata = {
  title: "My ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme
          appearance="dark"
          accentColor="plum"
          grayColor="mauve"
          radius="large"
        >
          {children}
          {/* <ThemePanel /> */}
        </Theme>
      </body>
    </html>
  );
}
